version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-runner:latest
    environment:
      MANIFEST_BRANCH: 'android-10.0'
      VERSION: '2.9.2-test'
      MAINTAINER: "PBRP Team"
      VENDOR: 'xiaomi'
      CODENAME: 'whyred'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      PB_ENGLISH: 'true'
      CHANGELOG: "Initial Build"
      EXTRA_CMD: "rm -f device/${VENDOR}/${CODENAME}/recovery/root/sbin/*.so"
    working_directory: /home/builder
    steps:
      - run:
          name: "CREATE KEEP-ALIVE SHELL"
          command: |
            [[ ! -d /tmp ]] && mkdir /tmp
            cat \<< EOF > /tmp/act.sh
            #!/bin/bash
            echo "\$$" > /tmp/act.pid
            while true; do
              echo "." && sleep 300
            done
            EOF
            chmod a+x /tmp/act.sh
      - run:
          name: "EXPORT ENVS"
          command: |
            printenv | sort -h > environ.txt
            grep environ.txt -e GitHubMail -e GitHubName -e GITHUB_TOKEN \
              -e CIRCLE_PROJECT_USERNAME -e CIRCLE_PROJECT_REPONAME -e CIRCLE_BRANCH -e CIRCLE_SHA1 \
              -e MANIFEST_BRANCH -e USE_SECRET_BOOTABLE -e SECRET_BR -e PBRP_BRANCH \
              -e VERSION -e MAINTAINER -e VENDOR -e CODENAME -e FLAVOR -e BUILD_LUNCH \
              -e TEST_BUILD -e PB_OFFICIAL -e EXTRA_CMD -e PB_ENGLISH -e CHANGELOG \
              > environments.file
            rm environ.txt
            cat environments.file
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "ALL IN REMOTE"
          command: |
            [[ ! -d /home/builder/.ccache ]] && mkdir -p /home/builder/.ccache
            cd /home/builder
            mkdir android && cd android
            /tmp/act.sh & docker run --privileged -i --name worker \
              --user builder -e USER_ID=1000 -e GROUP_ID=1000 \
              --env-file "/home/builder/environments.file" \
              -v "/home/builder/:/home/builder/:rw,z" \
              -v "${pwd}:/home/builder/android/:rw,z" \
              -v "/home/builder/.ccache:/srv/ccache:rw" \
              --workdir /home/builder \
              fr3akyphantom/droid-builder:focal bash \<< EOF
            set -eo pipefail
            set
            mkdir android && cd android
            # SANITY CHECKS & GIT SETUP
            if [[ -z $GitHubMail ]]; then echo -e "You haven't configured GitHub E-Mail Address." && exit 1; fi
            if [[ -z $GitHubName ]]; then echo -e "You haven't configured GitHub Username." && exit 1; fi
            if [[ -z $GITHUB_TOKEN ]]; then echo -e "You haven't configured GitHub Token.\nWithout it, recovery can't be published." && exit 1; fi
            if [[ -z $MANIFEST_BRANCH ]]; then echo -e "You haven't configured PitchBlack Recovery Project Manifest Branch." && exit 1; fi
            if [[ -z $VENDOR ]]; then echo -e "You haven't configured Vendor name." && exit 1; fi
            if [[ -z $CODENAME ]]; then echo -e "You haven't configured Device Codename." && exit 1; fi
            if [[ -z $BUILD_LUNCH ]] && [[ -z $FLAVOR ]]; then echo -e "Set at least one variable. BUILD_LUNCH or FLAVOR." && exit 1; fi
            # Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global credential.helper store
            git config --global color.ui true
            # Use Google Git Cookies for Smooth repo-sync
            git clone -q "https://$GITHUB_TOKEN@github.com/$GitHubName/google-git-cookies.git" &> /dev/null
            bash google-git-cookies/setup_cookies.sh
            rm -rf google-git-cookies
            # threads
            THREADCOUNT=$(nproc --all)
            echo -en "Available CPU Threads - " && echo ${THREADCOUNT}
            if [[ ${THREADCOUNT} -gt 8 ]]; then MAKEJOB=${THREADCOUNT}
            elif [[ ${THREADCOUNT} -gt 4 && ${THREADCOUNT} -lt 8 ]]; then MAKEJOB=8
            elif [[ ${THREADCOUNT} -eq 4 ]]; then MAKEJOB=${THREADCOUNT}
            elif [[ ${THREADCOUNT} -eq 2 ]]; then MAKEJOB=4
            fi
            # sync
            echo -e "Initializing PBRP repo sync..."
            repo init -q -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${MANIFEST_BRANCH} --depth 1
            /tmp/act.sh & repo sync -c -q --force-sync --no-clone-bundle --no-tags -j${MAKEJOB}
            # clean unneeded files
            rm -rf development/apps/ development/samples/ packages/apps/
            # use pb-10.0
            rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb-10.0 --depth 1 vendor/pb
            rm vendor/pb/vendorsetup.sh
            if [[ -n ${USE_SECRET_BOOTABLE} ]]; then
              [[ -n ${PBRP_BRANCH} ]] && unset PBRP_BRANCH
              [[ -z ${SECRET_BR} ]] && SECRET_BR="android-9.0"
              rm -rf bootable/recovery
              git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/pbrp_recovery_secrets -b ${SECRET_BR} --single-branch bootable/recovery
            elif [[ -n ${PBRP_BRANCH} ]]; then
              rm -rf bootable/recovery
              git clone --quiet --progress https://github.com/PitchBlackRecoveryProject/android_bootable_recovery -b ${PBRP_BRANCH} --single-branch bootable/recovery
            fi
            echo -e "\nGetting the Device Tree on place"
            if [[ "${CIRCLE_PROJECT_USERNAME}" == "PitchBlackRecoveryProject" ]]; then
              git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
            else
              git clone https://$GITHUB_TOKEN@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
            fi
            ls -lA .
            if [[ -n $EXTRA_CMD ]]; then
              eval "$EXTRA_CMD"
              cd /home/builder/android/
            fi
            JAVA_OPTS=${JAVA_OPTS:+" -Xmx8G "}
            echo -en "Current Username is - " && whoami
            echo -e "\nPreparing Delicious Lunch..."
            export ALLOW_MISSING_DEPENDENCIES=true
            source build/envsetup.sh
            if [[ -n $BUILD_LUNCH ]]; then
              lunch ${BUILD_LUNCH}
            elif [[ -n $FLAVOR ]]; then
              lunch omni_${CODENAME}-${FLAVOR}
            fi
            make -j${MAKEJOB} recoveryimage
            echo -e "\nYummy Recovery is Served.\n"
            # deploy
            export TEST_BUILDFILE=$(find $(pwd)/out/target/product/${CODENAME}/PitchBlack*-UNOFFICIAL.zip 2>/dev/null)
            export TEST_BUILDIMG=$(find $(pwd)/out/target/product/${CODENAME}/recovery.img 2>/dev/null)
            mkdir upload
            cp ${TEST_BUILDFILE} ${TEST_BUILDIMG} upload/
            # release
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Test Release for $(echo $CODENAME)" -b "PBRP $(echo $VERSION)" -c ${CIRCLE_SHA1} -delete ${VERSION}-test upload/
            echo -e "\n\nAll Done Gracefully\n\n"
            EOF
            echo -en "act-shell pid number is - " && cat /tmp/act.pid
            ACTPID=$(cat /tmp/act.pid) && kill -s SIGTERM ${ACTPID}

workflows:
  version: 2
  all_builder:
    jobs:
      - build:
          filters:
            branches:
              only: "android-10.0-remote"
          context: personal-envs
