version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-runner:latest
    environment:
      MANIFEST_BRANCH: 'android-10.0'
      VERSION: '2.9.2-test'
      MAINTAINER: "PBRP Team"
      VENDOR: 'xiaomi'
      CODENAME: 'whyred'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      PB_ENGLISH: 'true'
      CHANGELOG: |
        - Initial Build with Android-10 Source
        - Used Q Kernel prebuilt from Ancient-Project
        - Use COMMON_LUNCH_CHOICES instead of vendorsetup
        - Fix recovery.fstab inclusion
        - Modify build product configuration
        - Remove a few prebuilt *.so binary from sbin, they are built from source
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "ALL IN REMOTE"
          command: |
            [[ ! -d /home/builder/.ccache ]] && mkdir -p /home/builder/.ccache
            cd /home/builder/
            docker run --privileged -i --name worker --user builder \
              -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) \
              -e GitHubMail="${GitHubMail}" -e GitHubName="${GitHubName}" -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
              -e CIRCLE_PROJECT_USERNAME="${CIRCLE_PROJECT_USERNAME}" -e CIRCLE_PROJECT_REPONAME="${CIRCLE_PROJECT_REPONAME}" \
              -e CIRCLE_BRANCH="${CIRCLE_BRANCH}" -e CIRCLE_SHA1="${CIRCLE_SHA1}" \
              -e MANIFEST_BRANCH="${MANIFEST_BRANCH}" -e PBRP_BRANCH="${PBRP_BRANCH}" \
              -e USE_SECRET_BOOTABLE="${USE_SECRET_BOOTABLE}" -e SECRET_BR="${SECRET_BR}" \
              -e VERSION="${VERSION}" -e VENDOR="${VENDOR}" -e CODENAME="${CODENAME}" \
              -e BUILD_LUNCH="${BUILD_LUNCH}" -e FLAVOR="${FLAVOR}" \
              -e MAINTAINER="${MAINTAINER}" -e CHANGELOG="${CHANGELOG}" \
              -e TEST_BUILD="${TEST_BUILD}" -e PB_OFFICIAL="${PB_OFFICIAL}" \
              -e PB_ENGLISH="${PB_ENGLISH}" -e EXTRA_CMD="${EXTRA_CMD}" \
              -v "${pwd}:/home/builder/:rw,Z" \
              -v "/home/builder/.ccache:/srv/ccache:rw" \
              --workdir /home/builder/ \
              fr3akyphantom/droid-builder:focal bash \<< EOF
            curl -sL https://gist.github.com/rokibhasansagar/6177067d1f610431ab4f419db86a2b4b/raw/build.remote.sh -o build.sh
            source build.sh
            EOF

workflows:
  version: 2
  all_builder:
    jobs:
      - build:
          filters:
            branches:
              only: "android-10.0-remote"
          context: personal-envs
